services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./internal/question/_prompt.md:/root/internal/question/_prompt.md
      - ./quiz.db:/root/quiz.db
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  quiz-agent-service:
    build: ./services/quiz_agent
    ports:
      - "50052:50052"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
volumes:
  ollama:
  quiz_data:
