# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quiz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quiz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nquiz.proto\x12\nquiz_agent\"\x07\n\x05\x45mpty\"\xbb\x01\n\x04Quiz\x12\x0f\n\x07quiz_id\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x16\n\x0e\x63orrect_answer\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x10\n\x08\x61_answer\x18\x07 \x01(\t\x12\x10\n\x08\x62_answer\x18\x08 \x01(\t\x12\x10\n\x08\x63_answer\x18\t \x01(\t\x12\x10\n\x08\x64_answer\x18\n \x01(\t2J\n\x10QuizAgentService\x12\x36\n\x0fGetQuizOfTheDay\x12\x11.quiz_agent.Empty\x1a\x10.quiz_agent.Quizb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quiz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_QUIZ']._serialized_start=36
  _globals['_QUIZ']._serialized_end=223
  _globals['_QUIZAGENTSERVICE']._serialized_start=225
  _globals['_QUIZAGENTSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
