// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Answer struct {
	ID        int64
	Answer    string
	Timestamp sql.NullTime
	IsActive  sql.NullBool
}

type Attempt struct {
	ID        int64
	UserID    int64
	QuizID    int64
	Answer    string
	IsCorrect sql.NullBool
	Timestamp sql.NullTime
}

type LeaderBoard struct {
	ID          int64
	UserID      int64
	TotalScore  sql.NullInt64
	LastUpdated sql.NullTime
}

type Question struct {
	ID        int64
	Question  string
	Answer    string
	Timestamp sql.NullTime
	IsActive  sql.NullBool
}

type Quiz struct {
	ID          int64
	QID         int64
	AID         int64
	Date        sql.NullTime
	IsActive    sql.NullBool
	OptionsJson string
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Timestamp sql.NullTime
}
