// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Attempt struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	QuizID    int64        `json:"quiz_id"`
	Answer    string       `json:"answer"`
	IsCorrect sql.NullBool `json:"is_correct"`
	Timestamp sql.NullTime `json:"timestamp"`
}

type LeaderBoard struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	TotalScore  sql.NullInt64 `json:"total_score"`
	LastUpdated sql.NullTime  `json:"last_updated"`
}

type Question struct {
	ID            int64          `json:"id"`
	Question      string         `json:"question"`
	CorrectAnswer string         `json:"correct_answer"`
	Timestamp     sql.NullTime   `json:"timestamp"`
	IsActive      sql.NullBool   `json:"is_active"`
	AAnswer       string         `json:"a_answer"`
	BAnswer       string         `json:"b_answer"`
	CAnswer       string         `json:"c_answer"`
	DAnswer       sql.NullString `json:"d_answer"`
}

type Quiz struct {
	ID          int64        `json:"id"`
	QID         int64        `json:"q_id"`
	AID         int64        `json:"a_id"`
	Date        sql.NullTime `json:"date"`
	IsActive    sql.NullBool `json:"is_active"`
	OptionsJson string       `json:"options_json"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Timestamp sql.NullTime `json:"timestamp"`
}
